apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: singapore-gateway-ensure-mce
spec:
  steps:
  - args:
    - |-
      #!/bin/bash
      set -e

      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"

      echo "Applying MultiClusterEngine Argo app"

      oc apply -f samples/singapore-gateway-pipelines/resources/multiclusterengine
    command:
    - /bin/bash
    - -c
    image: quay.io/zkayyali812/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
