apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advanced-cluster-management
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: backup-and-restore/resources/operators/advanced-cluster-management
    repoURL: 'https://github.com/zkayyali812/pipeline-samples.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-sa-cluster-admin
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
