apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-upstream-acm-and-hypershift-deployment
spec:
  params:
  - name: clusterPoolName
    type: string
    description: The name of the clusterpool to use
    default: "hypershift-cluster-pool"
  - name: clusterClaimName
    type: string
    description: The name of the clusterclaim to claim
    default: "spoke-cluster"
  - name: clusterClaimLifetime
    type: string
    description: The length of the lifetime of the clusterclaim. Default 8h
    default: "8h"
  - name: namespace
    type: string
    description: The namespace to deploy ACM onto the target cluster
    default: "open-cluster-management"
  - name: snapshot
    type: string
    description: The upstream SNAPSHOT to used to deploy ACM
    default: "2.0-latest"
  tasks:
  - name: fetch-repo-samples
    params:
    - name: url
      value: https://github.com/zkayyali812/pipeline-samples.git
    - name: revision
      value: main
    - name: deleteExisting
      value: "true"
    - name: subdirectory
      value: "samples"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: validate-parameters
    params:
    - name: clusterPoolName
      value: $(params.clusterPoolName)
    - name: clusterClaimLifetime
      value: $(params.clusterClaimLifetime)
    taskRef:
      kind: Task
      name: deploy-acm-hyper-param-validation
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: checkout-cluster
    params:
    - name: clusterClaimName
      value: $(params.clusterClaimName)
    - name: clusterPoolName
      value: $(params.clusterPoolName)
    - name: clusterClaimLifetime
      value: $(params.clusterClaimLifetime)
    runAfter:
    - fetch-repo-samples
    - validate-parameters
    taskRef:
      kind: Task
      name: deploy-acm-hyper-checkout-cluster
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: login-to-cluster
    params:
    - name: username
      value: "$(tasks.checkout-cluster.results.username)"
    - name: password
      value: "$(tasks.checkout-cluster.results.password)"
    - name: api
      value: "$(tasks.checkout-cluster.results.api)"
    runAfter:
    - checkout-cluster
    taskRef:
      kind: Task
      name: deploy-acm-hyper-login-to-cluster
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: ensure-acm-deploy-prereqs
    params:
    - name: namespace
      value: "$(params.namespace)"
    - name: snapshot
      value: "$(params.snapshot)"
    - name: imagePullSecret
      value: "$(tasks.checkout-cluster.results.imagePullSecret)"
    runAfter:
    - login-to-cluster
    taskRef:
      kind: Task
      name: deploy-us-acm-hyper-prereqs
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: apply-acm
    params:
    - name: namespace
      value: $(params.namespace)
    - name: snapshot
      value: "$(params.snapshot)"
    runAfter:
    - ensure-acm-deploy-prereqs
    taskRef:
      kind: Task
      name: deploy-acm-hyper-apply-sub
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: apply-mch
    params:
    - name: namespace
      value: $(params.namespace)
    runAfter:
    - apply-acm
    taskRef:
      kind: Task
      name: deploy-us-acm-hyper-apply-mch
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: apply-hypershiftdeployment
    params:
    - name: namespace
      value: $(params.namespace)
    runAfter:
    - apply-mch
    taskRef:
      kind: Task
      name: deploy-us-acm-hyper-apply-hyper-deployment
    workspaces:
    - name: source
      workspace: shared-workspace
  workspaces:
  - name: shared-workspace
