apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  annotations:
    installer.open-cluster-management.io/mce-subscription-spec: '{"channel": "stable-2.0","installPlanApproval": "Automatic","name": "multicluster-engine","source": "multiclusterengine-catalog","sourceNamespace": "openshift-marketplace"}'
  name: multiclusterhub
spec:
  imagePullSecret: acm-pull-secret
  overrides:
    components:
    - enabled: true
      name: hypershift-preview
    - enabled: true
      name: multiclusterhub-repo
    - enabled: false
      name: search
    - enabled: false
      name: management-ingress
    - enabled: false
      name: console
    - enabled: false
      name: insights
    - enabled: true
      name: grc
    - enabled: true
      name: cluster-lifecycle
    - enabled: false
      name: volsync
    - enabled: true
      name: multicluster-engine
    - enabled: false
      name: cluster-backup
    - enabled: false
      name: cluster-proxy-addon
    - enabled: false
      name: assisted-service
    - enabled: false
      name: discovery
    - enabled: false
      name: hive
    - enabled: false
      name: console-mce
