apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: backup-and-restore
spec:
  params:
  - name: clusterPoolName
    type: string
    description: The name of the clusterpool to use
    default: "hypershift-cluster-pool"
  - name: clusterClaimName
    type: string
    description: The name of the clusterclaim to claim
    default: "spoke-cluster"
  - name: clusterClaimLifetime
    type: string
    description: The length of the lifetime of the clusterclaim. Default 8h
    default: "8h"
  tasks:
  - name: fetch-repo-samples
    params:
    - name: url
      value: https://github.com/zkayyali812/pipeline-samples.git
    - name: revision
      value: main
    - name: deleteExisting
      value: "true"
    - name: subdirectory
      value: "samples"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: validate-parameters
    params:
    - name: clusterPoolName
      value: $(params.clusterPoolName)
    - name: clusterClaimLifetime
      value: $(params.clusterClaimLifetime)
    taskRef:
      kind: Task
      name: backup-and-restore-param-validation
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: checkout-hub-cluster
    params:
    - name: clusterClaimName
      value: $(params.clusterClaimName)
    - name: clusterPoolName
      value: $(params.clusterPoolName)
    - name: clusterClaimLifetime
      value: $(params.clusterClaimLifetime)
    runAfter:
    - fetch-repo-samples
    - validate-parameters
    taskRef:
      kind: Task
      name: backup-and-restore-checkout-cluster
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: login-to-hub-cluster
    params:
    - name: username
      value: "$(tasks.checkout-hub-cluster.results.username)"
    - name: password
      value: "$(tasks.checkout-hub-cluster.results.password)"
    - name: api
      value: "$(tasks.checkout-hub-cluster.results.api)"
    runAfter:
    - checkout-hub-cluster
    taskRef:
      kind: Task
      name: backup-and-restore-login-to-cluster
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: configure-cluster
    runAfter:
    - login-to-hub-cluster
    taskRef:
      kind: Task
      name: backup-and-restore-configure-cluster
    workspaces:
    - name: source
      workspace: shared-workspace
  workspaces:
  - name: shared-workspace
