apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mce-operator-subscription
spec:
  channel: stable-2.0
  installPlanApproval: Automatic
  name: multicluster-engine
  source: multiclusterengine-catalog
  sourceNamespace: openshift-marketplace
