apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mce-deploy-pipeline-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: gp2
  volumeMode: Filesystem
