apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ensure-mce-sub-is-running
spec:
  params:
  - name: namespace
    default: multicluster-engine
    description: The namespace to deploy MCE into
    type: string
  - name: snapshot
    default: 2.5.0-SNAPSHOT
    description: The snapshot used to deploy MCE
    type: string
  steps:
  - args:
    - |-
      #!/bin/bash
      set -e

      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"

      _CHANNEL="stable-$(echo $(inputs.params.snapshot) | cut -c1-3)"

      existingCSV=$(oc get sub mce-operator-subscription -n $(inputs.params.namespace) -o yaml | yq eval '.status.currentCSV' -)
      if [[ "$existingCSV" != "" ]]; then
          echo "Existing MCE install exists"
          echo $existingCSV
          oc delete csv $existingCSV -n $(inputs.params.namespace)
          oc delete sub -n $(inputs.params.namespace) mce-operator-subscription
      else
          echo "Existing MCE install does not exist"
      fi

      oc apply -f samples/mce-deploy/resources/mce_operatorgroup.yaml -n $(inputs.params.namespace)
      oc patch og default -n $(inputs.params.namespace) --type=merge -p '{ "spec":  { "targetNamespaces" : ["$(inputs.params.namespace)"]}}'

      _TEMPLATE="apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: mce-operator-subscription
        namespace: $(inputs.params.namespace)
      spec:
        channel: ${_CHANNEL}
        installPlanApproval: Automatic
        name: multicluster-engine
        source: multiclusterengine-catalog
        sourceNamespace: openshift-marketplace"
      echo "$_TEMPLATE" | oc apply -f -

      _ATTEMPTS=0
      until oc get sub mce-operator-subscription -n $(inputs.params.namespace) -o jsonpath='{.status.currentCSV}' | grep -q "multicluster";
      do 
          echo "Waiting for CSV..."
          _ATTEMPTS=$((_ATTEMPTS + 1))
          sleep 5;
          if [[ $_ATTEMPTS == 5 ]]; then
              echo "Failed to find the CSV in allotted time"
              exit 1
          fi
      done

      _CURRENT_CSV=$(oc get sub mce-operator-subscription -n $(inputs.params.namespace) -o jsonpath='{.status.currentCSV}')

      _ATTEMPTS=0
      until oc get csv ${_CURRENT_CSV} -n $(inputs.params.namespace) -ojsonpath='{.status.phase}' | grep "Succeeded";
      do 
          echo "Waiting for CSV to installation to complete..."
          _ATTEMPTS=$((_ATTEMPTS + 1))
          sleep 15;
          if [[ $_ATTEMPTS == 10 ]]; then
              echo "The CSV failed to install in the allotted time"
              exit 1
          fi
      done

    command:
    - /bin/bash
    - -c
    image: quay.io/zkayyali812/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
