apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ensure-hypershift-is-installed-hack
spec:
  params:
  - name: namespace
    default: multicluster-engine
    description: The namespace to deploy HyperShift into
    type: string
  steps:
  - args:
    - |-
      #!/bin/bash
      set -e

      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"

      echo "Ensuring HyperShift is installed through a manual hack for now ..."
      oc apply -f samples/mce-deploy/resources/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
      helm install hypershift-preview samples/mce-deploy/resources/hypershift --namespace $(inputs.params.namespace)

    command:
    - /bin/bash
    - -c
    image: quay.io/zkayyali812/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
