apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ensure-params-are-valid
spec:
  params:
  - name: clusterPoolName
    default: ""
    description: The namespace to search for the clusterpool
    type: string
  - name: clusterPoolNamespace
    default: ""
    description: The name of the clusterpool to use
    type: string
  - name: clusterClaimLifetime
    default: ""
    description: The length of the lifetime of the clusterclaim
    type: string
  - name: imagePullSecret
    default: ""
    description: The imagePullSecret used to pull the ACM images. Must exist in clusterPoolNamespace
    type: string
  steps:
  - args:
    - |-
      #!/bin/bash
      set -e

      # Validate Clusterpool exists
      # Validate clusterClaimLifetime ends in 'h'
      # Validates imagePullSecretExists

      _NAMESPACE=$(inputs.params.clusterPoolNamespace)

      echo "For help with script see instrctions- https://github.com/zkayyali812/pipeline-samples"

      oc get clusterpool -n ${_NAMESPACE} $(inputs.params.clusterPoolName)
      if [[ $? == 0 ]]; then
        echo "Clusterpool exists"
      else
        echo "Unable to locate clusterpool: $(inputs.params.clusterPoolName) in namespace: $(inputs.params.clusterPoolNamespace)"
        exit 1
      fi

      _CLUSTERCLAIMLIFETIME=$(inputs.params.clusterClaimLifetime)
      if [[ "${_CLUSTERCLAIMLIFETIME: -1}" == 'h' ]]; then
        echo "ClusterClaimLifetime is valid"
      else
        echo "clusterClaimLifetime must end in 'h'"
        exit 1
      fi

      oc get secret -n ${_NAMESPACE} $(inputs.params.imagePullSecret)
      if [[ $? == 0 ]]; then
        echo "imagePullSecret exists"
      else
        echo "Unable to locate imagePullSecret: $(inputs.params.imagePullSecret) in namespace: $(inputs.params.clusterPoolNamespace)"
        exit 1
      fi
      echo "Params are valid"
    command:
    - /bin/bash
    - -c
    image: quay.io/zkayyali812/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
