apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ensure-mce-is-running
spec:
  params:
  - name: namespace
    default: open-cluster-management
    description: The namespace to deploy MCE into
    type: string
  - name: imagePullSecret
    default: multiclusterhub-operator-pull-secret
    description: The image pull secret used to deploy the catalogsources in 'openshift-marketplace' namespace
    type: string
  steps:
  - args:
    - |-
      #!/bin/bash
      set -e

      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"

      oc apply -f samples/mce-deploy/resources/multiclusterengine.yaml

      _ATTEMPTS=0
      until oc get mce multiclusterengine-sample -o jsonpath={'.status.phase'} | grep "Available";
      do 
          echo "Waiting for MCE to enter a Available state..."
          _ATTEMPTS=$((_ATTEMPTS + 1))
          sleep 15;
          if [[ $_ATTEMPTS == 30 ]]; then
              echo "Failed to install the MCE in allotted time"
              exit 1
          fi
      done

    command:
    - /bin/bash
    - -c
    image: quay.io/zkayyali812/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
