apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-ds-acm-hyper-apply-hyper-deployment
spec:
  params:
  - name: namespace
    default: open-cluster-management
    description: The namespace to deploy MCE into
    type: string
  steps:
  - args:
    - |-
      #!/bin/bash
      set -e

      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"
      oc project multicluster-engine
      
      oc apply -f samples/downstream-acm/resources/hypershiftdeployment.yaml

    command:
    - /bin/bash
    - -c
    image: quay.io/zkayyali812/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
