apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-ds-acm-hyper-apply-hyper-deployment
spec:
  params:
  - name: namespace
    default: open-cluster-management
    description: The namespace to deploy MCE into
    type: string
  steps:
  - args:
    - |-
      #!/bin/bash
      set -e

      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"

      oc project multicluster-engine
      oc create ns clusters || true
      oc apply -f samples/downstream-acm/resources/hypershiftdeployment.yaml

       _ATTEMPTS=0
      until oc get hostedcluster hypershift-demo -n clusters | grep "hypershift-demo";
      do 
          echo "Waiting for HostedCluster to be deployed from HyperShiftDeployment"
          _ATTEMPTS=$((_ATTEMPTS + 1))
          sleep 15;
          if [[ $_ATTEMPTS == 10 ]]; then
              echo "The hostedcluster did not come up in the allotted time"
              exit 1
          fi
      done
      
      echo "Sleeping 5 mins before applying workaround ..."
      sleep 300

      echo "Applying Temporary workaround ..."
      oc annotate -n clusters hostedcluster/hypershift-demo hypershift.openshift.io/control-plane-operator-image=quay.io/hypershift/hypershift-operator:latest

      _ATTEMPTS=0 
      echo "Waiting for HostedCluster deployment to complete ..."
      until oc get hostedcluster -n clusters hypershift-demo -o yaml | yq eval '.status.version.history.[0].state' - | grep "Completed";
      do 
          echo "$_ATTEMPTS/30: Waiting for HostedCluster deployment to be complete... Sleeping 1 min"
          _ATTEMPTS=$((_ATTEMPTS + 1))
          sleep 60;
          if [[ $_ATTEMPTS == 30 ]]; then
              echo "The hostedcluster not come up in the allotted time"
              exit 1
          fi
      done

      echo "HostedCluster deployed successfully."
      exit 0
    command:
    - /bin/bash
    - -c
    image: quay.io/zkayyali812/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
