apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: HypershiftDeployment
metadata:
  name: hypershift-demo
  namespace: multicluster-engine
spec:
  targetManagedCluster: local-cluster
  targetNamespace: clusters       # issue see https://github.com/stolostron/hypershift-deployment-controller/issues/30
  override: MANIFESTWORK
  infrastructure:
    cloudProvider:
      name: acm-credentials
    configure: true
    platform:
      aws:
        region: us-east-2
