apiVersion: v1
kind: Secret
metadata:
  name: singapore-gateway-ocm-credentials
stringData:
  ocmToken: "" # Retrievable from - https://qaprodauth.cloud.redhat.com/openshift/token/show
  awsAccountID: "" # AWS Account ID - https://docs.aws.amazon.com/IAM/latest/UserGuide/console_account-alias.html#FindingYourAWSId
  awsAccessKeyID: "" # AWS Access Key ID - https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys
  awsSecretAccessKey: "" # AWS Secret Access Key - https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys
  ocpVersion: "" # The OCP Version to deploy - ex. 4.10.6
  provider: "aws" # Currently only supports aws. OSD can be configured for GCP as well, but have not tested on GCP yet
  computeNodes: "4" # Number of compute nodes
  region: "" # Cloud provider region - ex - us-east-1
  clusterAdminUser: "" # The admin user to create to configure the cluster. Required to be able to deploy MCE
  idpGithubTeams: "" # The GH Team to add to the cluster for authentication - ex <ORG>/<TEAM>
  idpGithubAdmins: "" # Github user IDs to make admins of the cluster. ex - userid1,userid2,userid3
  idpClientID: "" # Github Client ID - https://docs.github.com/en/rest/guides/basics-of-authentication#registering-your-app
  idpClientSecret: "" # Github Client Secret - https://docs.github.com/en/rest/guides/basics-of-authentication#registering-your-app
  globalPullSecret: >-
    "" 
  # Should resemble - 
  # {
  #   "auths": {
  #     "cloud.openshift.com": {
  #       "auth": "",
  #       "email": ""
  #     },
  #     "quay.io:443": {
  #       "auth": "",
  #     },
  #     ...
  #   }
  # }
  # Global Pull Secret. To deploy downstream builds ensure the `quay.io:443` auth is filled
  # Can be retrieved in 2 ways.
  # Method 1 - Retrieve pull secret from UI and edit
  # 1. Go to - https://qaprodauth.cloud.redhat.com/openshift/downloads
  # 2. Scroll to bottom. Find 'Tokens' section. Dropdown 'Pull secret' and click 'Download'.
  # 3. Download file - 'pull_secret.txt'
  # Method 2 - Retrieve pull secret from active OCP cluster
  # 1. oc get secret/pull-secret -n openshift-config --template='{{index .data ".dockerconfigjson" | base64decode}}' > pull_secret.txt
  
  # After retrieving the 'pull-secret.txt' file, we can add the 'quay.io:443' section and up
  # 1. oc registry login --registry="quay.io:443" --auth-basic="${DOCKER_USER}:${DOCKER_PASS}" --to=pull_secret.txt
  # 2. Copy pull_secret.txt and add contents to value of this secret.
type: Opaque
