apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.org }}:{{ .Chart.Name }}:hypershiftDeployment-leader-election
  namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.org }}:{{ .Chart.Name }}:hypershiftDeployment-leader-election
subjects:
- kind: ServiceAccount
  name: hypershift-deployment
  namespace: {{ .Values.global.namespace }}
