apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: multiclusterengine-catalog
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  displayName: MultiCluster Engine
  image: quay.io:443/acm-d/mce-custom-registry:2.5.0-DOWNSTREAM-2022-04-21-01-26-54
  publisher: Red Hat
  sourceType: grpc
