apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine-sample
spec:
  overrides:
    components:
      - enabled: true
        name: managed-service-account
