apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: default
  namespace: multicluster-engine
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - "multicluster-engine"
