apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: default
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - open-cluster-management
