apiVersion: v1
data:
  additionalTrustBundle: ""
  aws_access_key_id: <AWS_ACCESS_KEY>
  aws_secret_access_key: <AWS_SECRET_ACCESS_KEY>
  baseDomain: <BASE_DOMAIN>
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""
  pullSecret: <PULL_SECRET
  ssh-privatekey: <SSH_PRIVATE_KEY>
  ssh-publickey: <SSH_PUBLIC_KEY>
kind: Secret
metadata:
  labels:
    cluster.open-cluster-management.io/credentials: ""
    cluster.open-cluster-management.io/type: aws
  name: hypershift-pipelines-acm-creds
  type: Opaque

---

apiVersion: v1
kind: Secret
metadata:
  name: hypershift-pipelines-hypershift-operator-oidc-provider-s3-credentials
data:
  bucket: <S3_BUCKET>
  credentials: <ENCRYPTED_AWS_CREDS>
  region: <REGION>
type: Opaque

---

apiVersion: v1
kind: Secret
metadata:
  name: hypershift-pipelines-multiclusterhub-operator-pull-secret
data:
  .dockerconfigjson: >-
    <QUAY_PULL_SECRET>
type: kubernetes.io/dockerconfigjson

