apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-acm-and-hypershift
spec:
  params:
  - name: clusterPoolNamespace
    type: string
    description: The namespace to search for the clusterpool
    default: "managed-services"
  - name: clusterPoolName
    type: string
    description: The name of the clusterpool to use
    default: "policy-aas-hubs"
  - name: clusterClaimName
    type: string
    description: The name of the clusterclaim to claim
    default: "spoke-cluster"
  - name: clusterClaimLifetime
    type: string
    description: The length of the lifetime of the clusterclaim. Default 8h
    default: "8h"
  - name: namespace
    type: string
    description: The namespace to deploy ACM onto the target cluster
    default: "open-cluster-management"
  - name: awsCredsSecret
    type: string
    description: The name of the AWS Credentials Secret used to deploy HyperShift. Must exist in clusterPoolNamespace
    default: "aws-creds"
  - name: S3BucketName
    type: string
    description: The name of the S3 Bucket used for HyperShift
    default: "s3-bucket-name"
  - name: region
    type: string
    description: The AWS region used
    default: "us-east-1"
  tasks:
  - name: fetch-repo-samples
    params:
    - name: url
      value: https://github.com/zkayyali812/pipeline-samples.git
    - name: revision
      value: main
    - name: deleteExisting
      value: "true"
    - name: subdirectory
      value: "samples"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: fetch-repo-hypershift
    params:
    - name: url
      value: https://github.com/openshift/hypershift.git
    - name: revision
      value: main
    - name: deleteExisting
      value: "true"
    - name: subdirectory
      value: "hypershift"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: fetch-repo-hypershift-deployment
    params:
    - name: url
      value: https://github.com/stolostron/hypershift-deployment-controller.git
    - name: revision
      value: main
    - name: deleteExisting
      value: "true"
    - name: subdirectory
      value: "hypershift-deployment"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: checkout-cluster
    params:
    - name: clusterClaimName
      value: $(params.clusterClaimName)
    - name: clusterPoolName
      value: $(params.clusterPoolName)
    - name: clusterPoolNamespace
      value: $(params.clusterPoolNamespace)
    - name: awsCredsSecret
      value: $(params.awsCredsSecret)
    - name: clusterClaimLifetime
      value: $(params.clusterClaimLifetime)
    runAfter:
    - fetch-repo-samples
    taskRef:
      kind: Task
      name: checkout-cluster
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: login-to-cluster
    params:
    - name: username
      value: "$(tasks.checkout-cluster.results.username)"
    - name: password
      value: "$(tasks.checkout-cluster.results.password)"
    - name: api
      value: "$(tasks.checkout-cluster.results.api)"
    runAfter:
    - checkout-cluster
    taskRef:
      kind: Task
      name: login-to-cluster
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: apply-acm-prereqs
    params:
    - name: namespace
      value: "$(params.namespace)"
    # - name: snapshotTag
    #   value: "$(params.snapshotTag)"
    runAfter:
    - login-to-cluster
    taskRef:
      kind: Task
      name: apply-acm-prereqs
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: apply-and-wait-for-subscription
    params:
    - name: namespace
      value: $(params.namespace)
    runAfter:
    - apply-acm-prereqs
    taskRef:
      kind: Task
      name: apply-and-wait-for-subscription
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: apply-and-wait-for-mch
    params:
    - name: namespace
      value: $(params.namespace)
    # - name: imagePullSecret
    #   value: $(params.imagePullSecret)
    runAfter:
    - apply-and-wait-for-subscription
    taskRef:
      kind: Task
      name: apply-and-wait-for-mch
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: apply-hypershift
    params:
    - name: namespace
      value: $(params.namespace)
    - name: S3BucketName
      value: $(params.S3BucketName)
    - name: region
      value: $(params.region)
    runAfter:
    - apply-acm-prereqs
    - fetch-repo-hypershift
    taskRef:
      kind: Task
      name: apply-hypershift
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: apply-hypershift-deployment-controller
    params:
    - name: namespace
      value: $(params.namespace)
    runAfter:
    - fetch-repo-hypershift-deployment
    - apply-hypershift
    taskRef:
      kind: Task
      name: apply-hypershift-deployment-controller
    workspaces:
    - name: source
      workspace: shared-workspace
  workspaces:
  - name: shared-workspace