apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-hypershift-deployment-controller
spec:
  params:
  - name: namespace
    default: open-cluster-management
    description: The namespace to deploy ACM into
    type: string
  steps:
  - args:
    - |-
      #!/bin/bash
      set -e

      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"

      export KUBECONFIG=${HOME}/.kube/config

      cd hypershift-deployment/
      oc apply -k config/deployment


    command:
    - /bin/bash
    - -c
    image: quay.io/zkayyali812/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
